App:
  RunMode: debug
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: sqlite3
  UserName: XXX
  Password: XXX
  Host: 127.0.0.1
  DBName: ${DB_NAME}
  TablePrefix: ${PREFIX_TABLE_NAME}
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  Path: ./var/db/games.db
Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
StoragePath:
  PDFFoldar: files
AI:
  APIKey: GOOGLE_API_KEY
  Model: gemini-2.0-flash
  Temperature: 1.0
  TopK: 40
  TopP: 0.95
  MaxOutputTokens: 1024
  Stream: False