# ---------- Build Stage ----------
FROM golang:1.23-bullseye AS builder

WORKDIR /app

# Copy go.mod and go.sum for dependency caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the Go binary
RUN go build -o main ./cmd/main

# ---------- Final Stage ----------
FROM debian:bullseye-slim

# Install wkhtmltopdf and dependencies
RUN apt-get update && apt-get install -y \
    wget \
    fontconfig \
    xfonts-base \
    xfonts-75dpi \
    libjpeg62-turbo \
    libxrender1 \
    libxtst6 \
    libpng-dev \
    && wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb \
    && dpkg -i wkhtmltox_0.12.6.1-2.bullseye_amd64.deb \
    && rm wkhtmltox_0.12.6.1-2.bullseye_amd64.deb \
    && apt-get clean

# Create necessary directories
RUN mkdir -p /app/files /app/storage/logs && chmod -R 777 /app/files /app/storage/logs

WORKDIR /app

# Copy Go binary
COPY --from=builder /app/main .

# Copy config files
COPY etc/config.yaml /app/etc/config.yaml

EXPOSE 8080

CMD ["./main"]
